In [1]:
pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)


2.1.3


In [5]:
import numpy as np

# Create a 1D array
data = [1, 2, 3, 4, 5]
array1 = np.array(data)
print(array1)
# Output: [1 2 3 4 5]

[1 2 3 4 5]


In [6]:
# Create a 2D array
data_2d = [[1, 2, 3], [4, 5, 6]]
array2 = np.array(data_2d)
print(array2)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [7]:
# Array of zeros
zeros = np.zeros((2, 3))  # 2 rows, 3 columns
print(zeros)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

# Array of ones
ones = np.ones((3, 2))  # 3 rows, 2 columns
print(ones)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

# Array with a range of values
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)
# Output: [0 2 4 6 8]

# Array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # Start, stop, number of points
print(linspace_array)
# Output: [0.   0.25 0.5  0.75 1.  ]

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", array.shape)  # Output: (2, 3)
print("Dimensions:", array.ndim)  # Output: 2
print("Data type:", array.dtype)  # Output: int64
print("Size:", array.size)  # Output: 6

Shape: (2, 3)
Dimensions: 2
Data type: int64
Size: 6


In [9]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)  # Output: [5 7 9]
print("Multiplication:", a * b)  # Output: [ 4 10 18]
print("Scalar multiplication:", a * 2)  # Output: [2 4 6]

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar multiplication: [2 4 6]


In [10]:
# Create an array
data = np.array([1, 4, 9])

print("Square root:", np.sqrt(data))  # Output: [1. 2. 3.]
print("Mean:", np.mean(data))  # Output: 4.666666666666667
print("Standard deviation:", np.std(data))  # Output: 3.559026084010437

Square root: [1. 2. 3.]
Mean: 4.666666666666667
Standard deviation: 3.2998316455372216


In [11]:
array = np.array([10, 20, 30, 40, 50])
print("First element:", array[0])  # Output: 10
print("Slice [1:4]:", array[1:4])  # Output: [20 30 40]

First element: 10
Slice [1:4]: [20 30 40]


In [12]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (1, 2):", array_2d[1, 2])  # Output: 6
print("First row:", array_2d[0, :])  # Output: [1 2 3]
print("Second column:", array_2d[:, 1])  # Output: [2 5 8]

Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]


In [13]:
data = np.array([10, 20, 30, 40, 50])
print(data[data > 25])  # Output: [30 40 50]

[30 40 50]


In [14]:
# Create a 1D array
array = np.arange(12)
print("Original:", array)
# Output: [ 0  1  2  3  4  5  6  7  8  9 10 11]

# Reshape to 3x4
reshaped = array.reshape(3, 4)
print("Reshaped:\n", reshaped)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
# Create two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
row_concat = np.concatenate((a, b), axis=0)
print("Row concatenation:\n", row_concat)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenate along columns (axis=1)
col_concat = np.concatenate((a, b), axis=1)
print("Column concatenation:\n", col_concat)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

Row concatenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Column concatenation:
 [[1 2 5 6]
 [3 4 7 8]]


In [16]:
# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Add them
result = array_2d + array_1d
print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [17]:
# Sales data (rows: weeks, columns: products)
sales = np.array([[120, 150, 130],
                  [110, 140, 125],
                  [130, 160, 135],
                  [115, 145, 120]])

# Calculate total sales per week
weekly_totals = np.sum(sales, axis=1)
print("Weekly totals:", weekly_totals)
# Output: [400 375 425 380]

# Calculate average sales per product
product_averages = np.mean(sales, axis=0)
print("Product averages:", product_averages)
# Output: [118.75 148.75 127.5 ]

# Filter weeks with total sales > 400
high_sales_weeks = sales[weekly_totals > 400]
print("High sales weeks:\n", high_sales_weeks)
# Output:
# [[130 160 135]]

Weekly totals: [400 375 425 380]
Product averages: [118.75 148.75 127.5 ]
High sales weeks:
 [[130 160 135]]
